import { Router } from "express";
import { apiKeysRouter } from "./apiKeys.js";
import { applicationsRouter } from "./applications.js";
import { entitlementsRouter } from "./entitlements.js";
import { environmentsRouter } from "./environments.js";
import { eventsRouter } from "./events.js";
import { healthRouter } from "./health.js";
import { integrationsRouter } from "./integrations.js";
import { meRouter } from "./me.js";
import { metersRouter } from "./meters.js";
import { organizationsRouter } from "./organizations.js";
import { permissionsRouter } from "./permissions.js";
import { plansRouter } from "./plans.js";
import { platformRouter } from "./platform.js";
import { rolesRouter } from "./roles.js";
import { serviceRouter } from "./service.js";
import { serviceScopesRouter } from "./serviceScopes.js";
import { subscriptionsRouter } from "./subscriptions.js";
import { usageRouter } from "./usage.js";
import { webhooksRouter } from "./webhooks.js";
import { applicationAccessRouter } from "./applicationAccess.js";
import { clientCommercialRouter } from "./clientCommercial.js";
import { commercialRouter } from "./commercial.js";
import { publicProposalsRouter } from "./publicProposals.js";
import { credentialProvisioningRouter } from "./credentialProvisioning.js";
import { platformCommercialReadRouter } from "./platformCommercialRead.js";

export const v1Router = Router();

v1Router.use(healthRouter);
v1Router.use(meRouter);
v1Router.use(serviceRouter);
v1Router.use(organizationsRouter);
v1Router.use(rolesRouter);
v1Router.use(permissionsRouter);
v1Router.use(applicationsRouter);
v1Router.use(applicationAccessRouter);
v1Router.use(plansRouter);
v1Router.use(subscriptionsRouter);
v1Router.use(entitlementsRouter);
v1Router.use(apiKeysRouter);
v1Router.use(serviceScopesRouter);
v1Router.use(webhooksRouter);
v1Router.use(eventsRouter);
v1Router.use(metersRouter);
v1Router.use(usageRouter);
v1Router.use(environmentsRouter);
v1Router.use(integrationsRouter);
v1Router.use(platformRouter);
v1Router.use(commercialRouter);
v1Router.use(platformCommercialReadRouter);
v1Router.use(publicProposalsRouter);
v1Router.use(clientCommercialRouter);
v1Router.use(credentialProvisioningRouter);
